apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - allow-egress-googleapis.yaml
  - frontend-gateway.yaml
  - frontend.yaml
patches:
  # frontend - delete frontend-external service (same as non-public-frontend component)
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend-external
      $patch: delete
