apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Datadog configuration (must be applied first)
  - datadog-secrets.yaml
  - datadog-agent.yaml
  - adservice.yaml
  - cartservice.yaml
  - chatbotservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  # - loadgenerator.yaml # During development, the loadgenerator module inside skaffold.yaml will be used.
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - shippingservice.yaml
  - tryonservice.yaml
  - mcp-service.yaml
  - peau-agent.yaml
  - video-generation.yaml
  - observability-insights-service.yaml
# components:
# - ../kustomize/components/cymbal-branding
# - ../kustomize/components/google-cloud-operations
# - ../kustomize/components/memorystore
# - ../kustomize/components/network-policies
# - ../kustomize/components/alloydb
# - ../kustomize/components/shopping-assistant
# - ../kustomize/components/spanner
# - ../kustomize/components/container-images-tag
# - ../kustomize/components/container-images-tag-suffix
# - ../kustomize/components/container-images-registry
