apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - network-policy-deny-all.yaml
  - network-policy-adservice.yaml
  - network-policy-cartservice.yaml
  - network-policy-checkoutservice.yaml
  - network-policy-currencyservice.yaml
  - network-policy-emailservice.yaml
  - network-policy-frontend.yaml
  - network-policy-loadgenerator.yaml
  - network-policy-paymentservice.yaml
  - network-policy-productcatalogservice.yaml
  - network-policy-recommendationservice.yaml
  - network-policy-redis.yaml
  - network-policy-shippingservice.yaml
